const foods = [
  "Chicken Biryani",
  "Zinger Burger",
  "Aloo Paratha",
  "Chana Chaat",
  "Daal Fry",
  "Chicken Karahi",
  "Paneer Tikka",
  "Shawarma",
  "Mutton Pulao",
  "Seekh Kabab",
  "Chapli Kabab",
  "Fried Fish",
  "Tandoori Chicken",
  "Nihari",
  "Kofta Curry",
  "Samosa",
  "Pakora",
  "Halwa Puri",
  "Lassi",
  "Kheer",
  "Ice Cream",
  "Falooda",
  "Burger",
  "Pizza",
  "Club Sandwich",
  "Beef Steak",
  "Fruit Salad",
  "Gulab Jamun",
  "Rasgulla",
  "Qeema Naan",
  "Chinese Rice",
  "Manchurian",
  "Hot & Sour Soup",
  "Chilli Chicken",
  "Spring Rolls",
  "Beef Biryani",
  "White Karahi",
  "Makhni Handi",
  "Chicken Malai Boti",
  "Roti",
  "Tikka Boti",
  "Katakat",
  "Shinwari Karahi",
  "Bakra Roast",
  "Kashmiri Chai",
  "Sheer Khurma",
  "Boiled Egg",
  "Toast with Butter",
  "Chargha",
  "Omelette",
  "Cornflakes",
  "Broast" ,
  "Haleem",
  "Rabri",
];
